import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "@/assets/styles/globals.css";
import QueryProvider from "@/layout/QueryProvider";
import LayoutProvider from "@/layout/LayoutProvider";
import ErrorHandler from "@/layout/ErrorHandler";

const notoSansKR = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSansKR.className} antialiased`}
      >
        <LayoutProvider>
          <ErrorHandler>
            <QueryProvider>{children}</QueryProvider>
          </ErrorHandler>
        </LayoutProvider>
      </body>
    </html>
  );
}
