import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "@/assets/styles/globals.css";
import QueryProvider from "@/layout/QueryProvider";
import LayoutProvider from "@/layout/LayoutProvider";
import ErrorHandler from "@/layout/ErrorHandler";
import AuthProvider from "@/layout/AuthProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/layout/AuthProvider/authOption";
import { NextAuthProvider } from "@/layout/NextAuthProvider";

const notoSansKR = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${notoSansKR.className} antialiased`}
      >
        <LayoutProvider>
          <ErrorHandler>
            <NextAuthProvider session={session}>
              <AuthProvider>
                <QueryProvider>{children}</QueryProvider>
              </AuthProvider>
            </NextAuthProvider>
          </ErrorHandler>
        </LayoutProvider>
      </body>
    </html>
  );
}
